import { supabase } from '../lib/supabaseClient'

// Função para criar/alterar a tabela reviews
export async function setupReviewsTable() {
  try {
    console.log('🔧 Configurando tabela reviews...')

    // SQL para criar a tabela
    const createTableSQL = `
      create table if not exists public.reviews (
        id bigint generated by default as identity primary key,
        user_id uuid,             -- opcional: id do usuário
        rating smallint not null, -- por exemplo: 1..5 (1 = muito inseguro, 5 = muito seguro)
        comment text,
        lat numeric(9,6) not null,
        lng numeric(9,6) not null,
        created_at timestamptz default now()
      );
    `

    // Executar criação da tabela
    const { error: createError } = await supabase.rpc('exec_sql', { 
      sql: createTableSQL 
    })

    if (createError) {
      console.error('❌ Erro ao criar tabela:', createError)
      return false
    }

    // SQL para configurar RLS
    const rlsSQL = `
      alter table public.reviews enable row level security;
      
      -- Política para leitura pública
      create policy if not exists "Reviews são públicos para leitura" 
        on public.reviews for select 
        using (true);

      -- Política para inserção autenticada
      create policy if not exists "Usuários autenticados podem inserir reviews" 
        on public.reviews for insert 
        with check (auth.uid() is not null);

      -- Política para atualização própria
      create policy if not exists "Usuários podem atualizar próprios reviews" 
        on public.reviews for update 
        using (auth.uid() = user_id);

      -- Política para deleção própria
      create policy if not exists "Usuários podem deletar próprios reviews" 
        on public.reviews for delete 
        using (auth.uid() = user_id);
    `

    const { error: rlsError } = await supabase.rpc('exec_sql', { 
      sql: rlsSQL 
    })

    if (rlsError) {
      console.warn('⚠️ Aviso ao configurar RLS:', rlsError)
    }

    console.log('✅ Tabela reviews configurada com sucesso!')
    return true

  } catch (error) {
    console.error('❌ Erro na configuração da tabela reviews:', error)
    return false
  }
}

// Função para testar a tabela
export async function testReviewsTable() {
  try {
    console.log('🧪 Testando tabela reviews...')

    // Testar inserção de dados de exemplo
    const testData = {
      rating: 5,
      comment: 'Local muito seguro e bem iluminado',
      lat: -23.5505,
      lng: -46.6333,
      user_id: null // Para teste sem usuário autenticado
    }

    const { data, error } = await supabase
      .from('reviews')
      .insert(testData)
      .select()

    if (error) {
      console.error('❌ Erro ao testar inserção:', error)
      return false
    }

    console.log('✅ Teste de inserção bem-sucedido:', data)

    // Testar leitura
    const { data: readData, error: readError } = await supabase
      .from('reviews')
      .select('*')
      .limit(5)

    if (readError) {
      console.error('❌ Erro ao testar leitura:', readError)
      return false
    }

    console.log('✅ Teste de leitura bem-sucedido:', readData?.length, 'registros')
    return true

  } catch (error) {
    console.error('❌ Erro no teste da tabela reviews:', error)
    return false
  }
}

// Função para obter estatísticas da tabela
export async function getReviewsStats() {
  try {
    const { count, error } = await supabase
      .from('reviews')
      .select('*', { count: 'exact', head: true })

    if (error) {
      console.error('❌ Erro ao obter estatísticas:', error)
      return null
    }

    const { data: ratingStats, error: statsError } = await supabase
      .from('reviews')
      .select('rating')

    if (statsError) {
      console.error('❌ Erro ao calcular estatísticas:', statsError)
      return { total: count }
    }

    const ratings = ratingStats?.map(r => r.rating) || []
    const avgRating = ratings.length > 0 
      ? ratings.reduce((a, b) => a + b, 0) / ratings.length 
      : 0

    return {
      total: count || 0,
      averageRating: Number(avgRating.toFixed(1)),
      ratingDistribution: {
        1: ratings.filter(r => r === 1).length,
        2: ratings.filter(r => r === 2).length,
        3: ratings.filter(r => r === 3).length,
        4: ratings.filter(r => r === 4).length,
        5: ratings.filter(r => r === 5).length,
      }
    }

  } catch (error) {
    console.error('❌ Erro ao obter estatísticas:', error)
    return null
  }
}