-- Script SQL para criar/alterar a tabela reviews
-- Execute este script no Supabase SQL Editor

-- Habilite se quiser (não obrigatório) e dependendo do plano:
-- CREATE EXTENSION IF NOT EXISTS postgis;

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid,             -- opcional: id do usuário
  rating smallint not null, -- por exemplo: 1..5 (1 = muito inseguro, 5 = muito seguro)
  comment text,
  lat numeric(9,6) not null,
  lng numeric(9,6) not null,
  created_at timestamptz default now()
);

-- índice espacial simples (útil se usar PostGIS)
-- create index if not exists reviews_gist on public.reviews using gist (st_setsrid(st_point(lng, lat), 4326));

-- Políticas de segurança RLS (Row Level Security)
alter table public.reviews enable row level security;

-- Política para permitir leitura para todos (reviews públicos)
create policy "Reviews são públicos para leitura" 
  on public.reviews for select 
  using (true);

-- Política para permitir inserção apenas para usuários autenticados
create policy "Usuários autenticados podem inserir reviews" 
  on public.reviews for insert 
  with check (auth.uid() is not null);

-- Política para permitir atualização apenas do próprio review
create policy "Usuários podem atualizar próprios reviews" 
  on public.reviews for update 
  using (auth.uid() = user_id);

-- Política para permitir deleção apenas do próprio review
create policy "Usuários podem deletar próprios reviews" 
  on public.reviews for delete 
  using (auth.uid() = user_id);

-- Comentários para documentação
comment on table public.reviews is 'Tabela de avaliações de segurança por localização geográfica';
comment on column public.reviews.rating is 'Avaliação de segurança: 1=muito inseguro, 5=muito seguro';
comment on column public.reviews.lat is 'Latitude em decimal (WGS84)';
comment on column public.reviews.lng is 'Longitude em decimal (WGS84)';