-- Execute este SQL no Console SQL do Supabase para configurar o sistema de reviews

-- Criar tabela reviews
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID,             -- opcional: id do usuário
  rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5), -- 1-5 (1 = muito inseguro, 5 = muito seguro)
  comment TEXT,
  lat NUMERIC(9,6) NOT NULL,
  lng NUMERIC(9,6) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Política para leitura pública
CREATE POLICY IF NOT EXISTS "Reviews são públicos para leitura" 
  ON public.reviews FOR SELECT 
  USING (true);

-- Política para inserção (qualquer pessoa pode inserir - remover auth.uid() is not null se quiser permitir anônimos)
CREATE POLICY IF NOT EXISTS "Qualquer pessoa pode inserir reviews" 
  ON public.reviews FOR INSERT 
  WITH CHECK (true);

-- Política para atualização própria (só funciona se user_id for preenchido)
CREATE POLICY IF NOT EXISTS "Usuários podem atualizar próprios reviews" 
  ON public.reviews FOR UPDATE 
  USING (auth.uid() = user_id OR user_id IS NULL);

-- Política para deleção própria (só funciona se user_id for preenchido)
CREATE POLICY IF NOT EXISTS "Usuários podem deletar próprios reviews" 
  ON public.reviews FOR DELETE 
  USING (auth.uid() = user_id OR user_id IS NULL);

-- Índice para melhorar performance em queries geográficas
CREATE INDEX IF NOT EXISTS reviews_location_idx ON public.reviews (lat, lng);

-- Índice para ordenação por data
CREATE INDEX IF NOT EXISTS reviews_created_at_idx ON public.reviews (created_at DESC);

-- Inserir alguns dados de exemplo
INSERT INTO public.reviews (rating, comment, lat, lng) VALUES 
(5, 'Área muito segura, bem iluminada e movimentada durante o dia', -23.5505, -46.6333),
(3, 'Razoavelmente seguro durante o dia, evite à noite', -23.5555, -46.6383),
(4, 'Boa área para caminhar, presença policial regular', -23.5455, -46.6283),
(2, 'Área com alguns problemas de segurança, cuidado extra necessário', -23.5605, -46.6433),
(5, 'Excelente localização, muito segura a qualquer hora', -23.5405, -46.6233),
(4, 'Local seguro com boa iluminação', -23.5355, -46.6183),
(3, 'Segurança moderada, evite horários muito tardios', -23.5655, -46.6483),
(5, 'Região comercial movimentada e segura', -23.5305, -46.6133)
ON CONFLICT DO NOTHING;

-- Verificar se tudo foi criado corretamente
SELECT 
  'reviews' AS table_name,
  COUNT(*) AS total_records,
  ROUND(AVG(rating), 2) AS average_rating,
  MIN(created_at) AS oldest_review,
  MAX(created_at) AS newest_review
FROM public.reviews;